language: node_js

sudo: 'required'

services:
  - 'docker'

before_install:
  - './.travis/main.sh'

script:
  - 'make test'
  - 'make image'

after_success:
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin ;
      make push-image ;
    fi

