version: '2.1'

services:
  bcnode:
    container_name: bcnode
    build:
      context: .
    image: trick77/bcnode:latest
    environment:
      - BC_MONITOR=false
      - BC_DEBUG=false
      - BC_LOG=info
    command: --ws --rovers --node --ui --miner-key ABCDEF
    volumes:
      - data:/home/bc/src/_data
      - ./conf:/src/config:ro
    ports:
    - "3000:3000"
    - "9090:9090"
    restart: unless-stopped

volumes:
  data:
